version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - ":children_crossing: dependencies"
    assignees:
      - sualeh
      - schemacrawler
